### PR TITLE
Include client with page

### PR DESCRIPTION
**Pull request by dns2utf8**
The code will require the [validator](https://github.com/spacedirectory/validator) at `https://validator.spacedirectory.org/` 

It is currently in progress.
I wonder about the best way to include the css.

### CODE REVIEW

**Comment by dbrgn** [comment]
Why not write ES2015? :)

**Comment by dns2utf8** [comment]
because this code runs even with IE9 😉 

When I use "the new stuff" I usually have some traffic staticstics, with 90% client support for these feature.
But I am open to PRs 😜

**Comment by dns2utf8** [comment]
So this should be ready for a first deployment.
It is still ugly, but it works for now.

**Comment by dbrgn** [comment]
It's still quite hacky, so I'd put a disclaimer there and merge :)

**Comment by dbrgn** [comment]
Merged in 91321fc5bd621286f4e89725414dab57fdc9fc0c

**Pull request closed without merging**
